# permissions for end users to edit mapreduces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mapreduce-editor-role
rules:
- apiGroups:
  - cache.k69s.io
  resources:
  - mapreduces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.k69s.io
  resources:
  - mapreduces/status
  verbs:
  - get
